----------------------------------Assignment - Case Study 1---------------------

---Q1: Display the number of states present in the LocationTable?
select Count(Distinct State) as No_of_states
from Location

---Q2 : How many products are of regular type?
select Count(Distinct Product) as No_of_products
from Product where Type='Regular'

---Q3 : How much spending has been done on marketing of product ID 1?
select Sum(Marketing) as Sum_of_MRK from fact where ProductID=1


---Q4 : What is the minimum sales of a product?
select Min(sales) as Min_Sales from fact

---Q5 : Display the max Cost of Good Sold (COGS)?
select Max(COGS) as Max_COGS from fact

---Q6 : Display the details of the product where product type is coffee?
Select ProductID from product
where Product_type='Coffee'

---Q7 : Display the details where total expenses are greater than 40?

select * from Fact
where Total_Expenses>40

---Q8: What is the average sales in area code 719?
select Avg(sales) as Avg_Sales from Fact where Area_Code=719

---Q9 : Find out the total profit generated by Colorado state?
select Sum(Ft.Profit) as Total_profit_by_Colorado from fact as FT
join Location as L on FT.Area_code=L.Area_code
where L.State='Colorado'

---Q10 : Display the average inventory for each product ID?
select ProductID, Avg(Inventory) as Avg_Inventory from Fact
Group by ProductID
Order by ProductID

---Q11. Display state in a sequential order in a Location Table?
select Distinct(State) from Location
Order by State

---Q12 : Display the average budget of the area code where the average budget margin should be greater than 100?

select Area_Code, Avg(Budget_Margin) as Avg_of_Budget_Margin_by_AreaCode from Fact
group by Area_Code
Having Avg(Budget_Margin)>100
Order by Area_Code

---Q13 : What is the total sales done on date 2010-01-01?

Select Sum(Sales) as Total_Sales from fact where date='	2010-01-01'

---Q14 : Display the average total expense of each product ID on an individual date?
Select date,ProductID, Avg(Total_Expenses) as Total_Expense from fact
Group by date,ProductID
Order by date,ProductID

---Q15 : Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code

select F.date,p.ProductID,P.Product_Type,P.Product,F.Sales,F.profit,L.State,L.Area_Code from Fact as F
Join location as L on F.Area_code=L.Area_Code
join Product as P on F.ProductID=P.ProductID

---Q16 : Display the rank without any gap to show the sales wise rank
Select sales, DENSE_RANK()Over(order by Sales desc) as D_Rank from Fact

---Q17 : Find the state wise profit and sales?
select LC.State, Sum(FT.Sales) as Total_Sales, Sum(FT.Profit) as Total_Profit from fact as FT
Join Location as LC on FT.Area_code=LC.Area_code
group by LC.State

---Q18 : Find the state wise profit and sales along with the productname?
select L.State,P.Product, Sum(FT.Profit) as Total_Profit, Sum(FT.Sales) as Total_Sales from Fact as FT
join Location as L on FT.Area_Code=L.Area_code
join Product as P on FT.ProductID=P.ProductID
group by L.State,P.Product
order by L.State,P.Product

---Q19 : If there is an increase in sales of 5%, calculate the increasedsales?
Select Sales,(Sales * 1.05) as Increases_Salesby5 from Fact

---Q20 : Find the maximum profit along with the product ID and producttype.
select P.ProductID,p.Product_type,Max(F.Profit) as Max_Profit from Fact as F
join Product as P on F.ProductID=P.ProductID
group by P.ProductID,P.Product_Type

---Q21 : Create a stored procedure to fetch the result according to the product type from Product Table?
create procedure Prod_Poc
@Type varchar(30)
as
Select * from Product where Product_Type=@Type
exec Prod_Poc 'Tea'

---Q22: Write a query by creating a condition in which if the total expenses is lessthan60 then it is a profit or else loss?
Select Total_Expenses,iif(Total_Expenses<60,'Profit','Loss') as Status from fact

---Q23 : Give the total weekly sales value with the date and product IDdetails. Useroll-up to pull the data in hierarchical order?

select Datepart(Week,Date) as Week,ProductID,Sum(Sales) as Weekwise_sales from Fact
group by Datepart(Week,Date),ProductID with rollup
Order by Datepart(Week,Date),ProductID

---Q24 : Apply union and intersection operator on the tables which consist of attribute area code.
select Area_code from Fact
union
Select Area_code from Location


select Area_code from Fact
intersect
Select Area_code from Location


---!25 : Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference?

create function Func_Prod
(@type varchar(50))
Returns Table
Return
(Select * from	Product where Product_Type=@Type)

Select * from Func_Prod('Tea')

---Q26 : Change the product type from coffee to tea where product IDis 1 andundoit?
Begin transaction
update Product set Product_Type='Tea' where ProductID=1

---Q27: Display the date, product ID and sales where total expenses are between 100 to 200

select date,ProductID,Sales from fact
where Total_Expenses between 100 and 200

---Q28 : Delete the records in the Product Table for regular type?
begin transaction
Delete from product where Product_Type='Tea'

Rollback transaction

---Q29 : Display the ASCII value of the fifth character from the columnProduct?
Select Product, Substring(Product,5,1) As Character, ASCII(Substring(Product,5,1)) as ASCII
from Product